services:
  express-backend:
    image: historytalk-express:latest
    container_name: historytalk-express
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://datdat2kk5:datdat2kk5@historytalkdb.l3pzqfp.mongodb.net/?appName=HistoryTalkDB
      - CORS_ORIGIN=http://localhost:3000
      - JWT_SECRET=hellowdp301letsgetthehighestgradepossible
      - JWT_EXPIRES_IN=7d
      - AI_SERVICE_URL=http://historytalk-ai:8001
      - PAYOS_CLIENT_ID=fca15eb2-1bf7-4341-a519-a305a0d517b3
      - PAYOS_API_KEY=fdf535de-f58f-4106-9b09-19560e36be4b
      - PAYOS_CHECKSUM_KEY=11ceadcd47d308491f28835eaccaa7dfcc48dcaaa6eca91cbfe79b7e0bd148eb
      - PAYOS_BASE_URL=https://api-merchant.payos.vn
      - PAYOS_RETURN_URL=https://history-talk-fe-topaz.vercel.app/payment/result
      - PAYOS_CANCEL_URL=https://history-talk-fe-topaz.vercel.app/payment/result
    networks:
      - historytalk-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M

networks:
  historytalk-net:
    external: true
    name: swd392_finalproject_historytalk_historytalk-net
