services:
  express-backend:
    image: historytalk-express:latest
    container_name: historytalk-express
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env.prod
    networks:
      - historytalk-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M

networks:
  historytalk-net:
    external: true
    name: swd392_finalproject_historytalk_historytalk-net
