name: Deploy Express Backend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 1. Di chuyển vào thư mục code Express ở repo độc lập
            cd /home/ec2-user/wdp301-backend
            
            # 2. Reset và Kéo code mới nhất từ nhánh main
            git reset --hard HEAD
            git pull origin main
            
            # 3. Build lại image (tối ưu, bypass lỗi buildx trên EC2)
            sudo docker build -t historytalk-express:latest .
            
            # 4. Chạy lại container express-backend
            sudo docker compose -f docker-compose.prod.yml up -d
            
            # 5. Dọn dẹp các image cũ để tránh rác ổ cứng
            sudo docker image prune -f
